-- CREATE USER TABLE
CREATE TABLE [User](
Id BIGINT NOT NULL UNIQUE,
CreatedAt DATETIME2 DEFAULT GETDATE()
CONSTRAINT PK_user_Id PRIMARY KEY(Id)
)
-- CREATE MEDIA TABLE
CREATE TABLE [Media](
Id VARCHAR(50) NOT NULL UNIQUE,
Title NVARCHAR(255) NOT NULL,
PosterPath VARCHAR(350),
CreatedAt DATETIME2 DEFAULT GETDATE()
CONSTRAINT PK_media_Id PRIMARY KEY(Id)
)
-- CONJUNCTION TABLE
CREATE TABLE UserMedia(
UserId BIGINT NOT NULL,
MediaId VARCHAR(50) NOT NULL
CONSTRAINT FK_UserMedia_UserId FOREIGN KEY(UserId) REFERENCES [User](Id) ON DELETE CASCADE,
CONSTRAINT FK_UserMedia_MediaId FOREIGN KEY(MediaId) REFERENCES [Media](Id) ON DELETE CASCADE
)